// <auto-generated />
using System;
using CoreDAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreDAL.Migrations
{
    [DbContext(typeof(OrionDbContext))]
    [Migration("20190609181535_OrionDBConnection")]
    partial class OrionDBConnection
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreDAL.Models.Employee", b =>
                {
                    b.Property<string>("code")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("annualsalary");

                    b.Property<DateTime>("dateofbirth");

                    b.Property<string>("gender");

                    b.Property<string>("name");

                    b.HasKey("code");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
